name: Docs

# Events that trigger this workflow
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v3.0.2

      - name: Set up JDK 16 💿
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'zulu'
          java-version: '16'
          java-package: jdk
          cache: 'gradle'

      - name: Build documentation 🛠️
        run: chmod +x gradlew && ./gradlew javadoc
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}
      - name: Finalize build 🪄
        run: touch build/docs/javadoc/.nojekyll

      - name: Deploy documentation 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.2
        with:
          branch: gh-pages
          folder: build/docs/javadoc
          clean: true
